
name: Release
on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository shortname (beta/esr91)
        required: true
        type: choice
        options:
        - esr91
      version:
        description: Thunderbird version
        required: true
        type: string
      buildnum:
        description: Version build iteration
        required: true
        type: string


jobs:
  Thunderbird:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: AppImageTool download
      run: |
        ./scripts/download_appimagetool.sh

    - name: runme.sh
      run: |
        ./scripts/runme.sh
      env:
        REPO: ${{ github.event.inputs.repo }}
        VERSION: ${{ github.event.inputs.version }}
        BUILD_NUMBER: ${{ github.event.inputs.buildnum }}

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: thunderbird-continuous-x86_64.AppImage
        path: 'artifacts/'

  Release:
    needs: [Thunderbird]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: thunderbird-continuous-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Thunderbird Stable AppImage Builds
        automatic_release_tag: esr91
        prerelease: false
        draft: false
        files: |
          thunderbird-continuous-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}

