
name: Release
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: Equivalent to "update channel" - beta, esr91
        required: true
        type: choice
        options:
        - esr91
        - beta
      version:
        description: Thunderbird version
        required: true
        type: string
      buildnum:
        description: Version build iteration
        required: true
        type: string


jobs:
  Thunderbird:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.inputs.release-tag }}
      VERSION: ${{ github.event.inputs.version }}
      BUILD_NUMBER: ${{ github.event.inputs.buildnum }}
    steps:
    - uses: actions/checkout@v2

    - name: AppImageTool download
      run: |
        ./scripts/download_appimagetool.sh

    - name: runme.sh
      run: |
        ./scripts/runme.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: 'artifacts/'

  Release:
    needs: [Thunderbird]
    runs-on: ubuntu-latest
    env:
      release_tag: ${{ github.event.inputs.release-tag }}
      release_version: ${{ github.event.inputs.version }}

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: public

    - name: Release Title
      run: |
        if [[ "$release_tag" =~ ^esr ]]; then
          echo "release_title=Stable" >> $GITHUB_ENV
        elif [[ "$release_tag" = beta ]]; then
          echo "release_title=Beta" >> $GITHUB_ENV
        else
          echo "::error file=release.yml::Invalid release tag $release_tag"
          exit 77
        fi
        pwd
        ls -laR

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Thunderbird ${{ env.release_title }} AppImage ${{ env.release_version }}
        automatic_release_tag: ${{ env.release_tag }}
        prerelease: false
        draft: false
        files: |
          *.AppImage
          *.AppImage.zsync
        repo_token: ${{ secrets.GITHUB_TOKEN }}

